[worldserver]
IndividualProgression.Enable = 1

IndividualProgression.VanillaPowerAdjustment = .5
IndividualProgression.VanillaHealingAdjustment = .5
IndividualProgression.TBCPowerAdjustment = .5
IndividualProgression.TBCHealingAdjustment = .5

IndividualProgression.QuestXPFix = 1

###
###
###

IndividualProgression.EnforceGroupRules = 0

IndividualProgression.BotOnlyAdjustments = 0

IndividualProgression.RequireNaxxStrathEntrance = 0

IndividualProgression.doableNaxx40Bosses_4H = 0
IndividualProgression.doableNaxx40Bosses_Gluth = 0
IndividualProgression.doableNaxx40Bosses_Patchwerk = 0
IndividualProgression.doableNaxx40Bosses_Razuvious = 0

IndividualProgression.MoltenCore.ManualRuneHandling = 1

IndividualProgression.MoltenCore.AqualEssenceCooldownReduction = 0

IndividualProgression.SerpentshrineCavern.RequireAllBosses = 1

IndividualProgression.TheEye.RequireAllBosses = 1

IndividualProgression.FishingFix = 1

IndividualProgression.SimpleConfigOverride = 1

IndividualProgression.DisableQuestMarkers = 1

IndividualProgression.DisableRDF = 1

IndividualProgression.MaxMonsterSight = 1

IndividualProgression.QuestMoneyAtLevelCap = 1

IndividualProgression.RepeatableVanillaQuestsXP = 1

IndividualProgression.ProgressionLimit = 0

IndividualProgression.StartingProgression = 0

IndividualProgression.TbcRacesUnlockProgression = 0

IndividualProgression.tbcRacesStartingProgression = 0

IndividualProgression.DeathKnightUnlockProgression = 13

IndividualProgression.DeathKnightStartingProgression = 13

IndividualProgression.RequiredZulGurubProgression = 3

IndividualProgression.RequiredZulAmanProgression = 12

IndividualProgression.DisableDefaultProgression = 0

IndividualProgression.CustomProgression = ""

IndividualProgression.AllowEarlyDungeonSet2 = 0

IndividualProgression.AllowEarlyScourgeBosses = 0

IndividualProgression.TBC.ArenaSeason = 1

IndividualProgression.WotLK.ArenaSeason = 5

IndividualProgression.VanillaPvpKillRequirement.Rank1 = 100
IndividualProgression.VanillaPvpKillRequirement.Rank2 = 200
IndividualProgression.VanillaPvpKillRequirement.Rank3 = 400
IndividualProgression.VanillaPvpKillRequirement.Rank4 = 800
IndividualProgression.VanillaPvpKillRequirement.Rank5 = 1400
IndividualProgression.VanillaPvpKillRequirement.Rank6 = 2000
IndividualProgression.VanillaPvpKillRequirement.Rank7 = 3000
IndividualProgression.VanillaPvpKillRequirement.Rank8 = 4500
IndividualProgression.VanillaPvpKillRequirement.Rank9 = 6000
IndividualProgression.VanillaPvpKillRequirement.Rank10 = 8000
IndividualProgression.VanillaPvpKillRequirement.Rank11 = 10000
IndividualProgression.VanillaPvpKillRequirement.Rank12 = 13000
IndividualProgression.VanillaPvpKillRequirement.Rank13 = 18000
IndividualProgression.VanillaPvpKillRequirement.Rank14 = 24000

IndividualProgression.VanillaPvpTitlesPersistAfterVanilla = 1

IndividualProgression.VanillaPvpEarnTitlesAfterVanilla = 0

IndividualProgression.BotAccountsEarnPvPTitles = 0

IndividualProgression.BotAccountsMaxLevel = 80

IndividualProgression.BotAccountsRegex = "^RNDBOT.*"

IndividualProgression.ExcludedAccountsRegex = ""

IndividualProgression.EnableAllSpellRanks = 0

IndividualProgression.EnableSetRepCommand = 0

IndividualProgression.LimitedSetRepCommand = 1

IndividualProgression.sharedFactionIdsRegex = "59|270|349|509|510|529|576|589|609|729|730|749|889|890|909"
